[application]
name = "kbo-gui"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[bundle]
identifier = "kbo"
publisher = "tmaklin"

[web.app]
title = "kbo-gui"
base_path = "kbo"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
